apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
    argocd.argoproj.io/sync-wave: "1"
  name: myjob
spec:
  ttlSecondsAfterFinished: 100
  template:
    spec:
      containers:
      - name: tool-container
        image: amsy810/tools:v2.0
        command: ["echo", "hello4"]
      restartPolicy: Never

---
apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    argocd.argoproj.io/hook: Skip
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
    argocd.argoproj.io/sync-wave: "1"
  name: myjob2
spec:
  ttlSecondsAfterFinished: 100
  template:
    spec:
      containers:
      - name: tool-container
        image: amsy810/tools:v2.0
        command: ["echo", "hello2-4"]
      restartPolicy: Never
