apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    argocd.argoproj.io/hook: Skip
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
    argocd.argoproj.io/sync-wave: "1"
  name: myjob
spec:
  ttlSecondsAfterFinished: 100
  template:
    spec:
      containers:
      - name: tool-container
        image: amsy810/tools:v2.0
        command: ["echo", "hello3"]
      restartPolicy: Never

