apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-test-deployment
  labels:
    app: go-test
spec:
  replicas: 3
  selector:
    matchLabels:
      app: go-test
  template:
    metadata:
      labels:
        app: go-test
    spec:
      containers:
      - name: go-test
        image: go-test
        imagePullPolicy: Never
        ports:
        - containerPort: 8080